# Generated by Django 4.0.2 on 2022-02-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_material_cycliccurve_material_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycliccurve',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='encurve',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='sncurve',
            name='Nf',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='sncurve',
            name='Sa',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='sncurve',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
