# Generated by Django 4.0.2 on 2022-02-22 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cycliccurve_name_alter_encurve_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('K', models.FloatField(max_length=200)),
                ('n', models.FloatField(max_length=200)),
                ('comment', models.CharField(max_length=1000)),
                ('material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.material')),
            ],
        ),
    ]
