# Generated by Django 4.0.2 on 2022-02-23 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_staticcurve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('type', models.CharField(max_length=200)),
                ('material_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.materialtype')),
            ],
        ),
        migrations.CreateModel(
            name='HoseStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('E_min40', models.FloatField()),
                ('E_plus23', models.FloatField()),
                ('E_plus100', models.FloatField()),
                ('comment', models.CharField(max_length=1000)),
                ('hose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hose')),
            ],
        ),
        migrations.CreateModel(
            name='HoseDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('E_min40', models.FloatField()),
                ('E_plus23', models.FloatField()),
                ('E_plus100', models.FloatField()),
                ('comment', models.CharField(max_length=1000)),
                ('hose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hose')),
            ],
        ),
    ]
