# Generated by Django 4.0.2 on 2022-02-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_hose_hosestatic_hosedynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosedynamic',
            name='nu_min40',
            field=models.FloatField(default=0.495),
        ),
        migrations.AddField(
            model_name='hosedynamic',
            name='nu_plus100',
            field=models.FloatField(default=0.495),
        ),
        migrations.AddField(
            model_name='hosedynamic',
            name='nu_plus23',
            field=models.FloatField(default=0.495),
        ),
        migrations.AddField(
            model_name='hosestatic',
            name='nu_min40',
            field=models.FloatField(default=0.495),
        ),
        migrations.AddField(
            model_name='hosestatic',
            name='nu_plus100',
            field=models.FloatField(default=0.495),
        ),
        migrations.AddField(
            model_name='hosestatic',
            name='nu_plus23',
            field=models.FloatField(default=0.495),
        ),
    ]
