# Generated by Django 4.0.2 on 2022-02-25 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_hosedynamic_nu_min40_hosedynamic_nu_plus100_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hosedynamic',
            old_name='E_min40',
            new_name='Dyn_E_min40',
        ),
        migrations.RenameField(
            model_name='hosedynamic',
            old_name='E_plus100',
            new_name='Dyn_E_plus100',
        ),
        migrations.RenameField(
            model_name='hosedynamic',
            old_name='E_plus23',
            new_name='Dyn_E_plus23',
        ),
        migrations.RenameField(
            model_name='hosedynamic',
            old_name='comment',
            new_name='Dyn_comment',
        ),
        migrations.RenameField(
            model_name='hosedynamic',
            old_name='hose_id',
            new_name='Dyn_hose_id',
        ),
        migrations.RenameField(
            model_name='hosedynamic',
            old_name='name',
            new_name='Dyn_name',
        ),
        migrations.RenameField(
            model_name='hosedynamic',
            old_name='nu_min40',
            new_name='Dyn_nu_min40',
        ),
        migrations.RenameField(
            model_name='hosedynamic',
            old_name='nu_plus100',
            new_name='Dyn_nu_plus100',
        ),
        migrations.RenameField(
            model_name='hosedynamic',
            old_name='nu_plus23',
            new_name='Dyn_nu_plus23',
        ),
        migrations.RenameField(
            model_name='hosestatic',
            old_name='E_min40',
            new_name='Stat_E_min40',
        ),
        migrations.RenameField(
            model_name='hosestatic',
            old_name='E_plus100',
            new_name='Stat_E_plus100',
        ),
        migrations.RenameField(
            model_name='hosestatic',
            old_name='E_plus23',
            new_name='Stat_E_plus23',
        ),
        migrations.RenameField(
            model_name='hosestatic',
            old_name='comment',
            new_name='Stat_comment',
        ),
        migrations.RenameField(
            model_name='hosestatic',
            old_name='hose_id',
            new_name='Stat_hose_id',
        ),
        migrations.RenameField(
            model_name='hosestatic',
            old_name='name',
            new_name='Stat_name',
        ),
        migrations.RenameField(
            model_name='hosestatic',
            old_name='nu_min40',
            new_name='Stat_nu_min40',
        ),
        migrations.RenameField(
            model_name='hosestatic',
            old_name='nu_plus100',
            new_name='Stat_nu_plus100',
        ),
        migrations.RenameField(
            model_name='hosestatic',
            old_name='nu_plus23',
            new_name='Stat_nu_plus23',
        ),
    ]
