# Generated by Django 4.0.2 on 2022-02-25 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_e_min40_hosedynamic_dyn_e_min40_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosedynamic',
            name='Dyn_name',
        ),
        migrations.RemoveField(
            model_name='hosestatic',
            name='Stat_name',
        ),
    ]
