# Generated by Django 4.0.2 on 2022-03-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_hosedynamic_dyn_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hose',
            name='type',
            field=models.CharField(choices=[('GOUIDER', 'Goudier'), ('ARCTIC NK', 'Arctic NK')], max_length=200),
        ),
    ]
