# Generated by Django 4.0.2 on 2022-03-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_hose_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hose',
            name='type',
            field=models.CharField(choices=[('Goodyer', 'Goodyer'), ('Arctic NK', 'Arctic NK')], max_length=200),
        ),
    ]
