# Generated by Django 4.0.2 on 2022-03-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_type_hose_type_s'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hose',
            old_name='type_s',
            new_name='type',
        ),
    ]
