# Generated by Django 4.0.2 on 2022-03-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_type_s_hose_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hose',
            name='type',
            field=models.CharField(choices=[('GOODYER', 'Goodyer'), ('ARCTIC NK', 'Arctic NK')], max_length=200),
        ),
    ]
