# Generated by Django 4.0.2 on 2022-03-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_hose_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hose',
            name='type',
            field=models.CharField(choices=[(' Conti ', ' Conti '), (' Maflow ', ' Maflow ')], max_length=200),
        ),
    ]
