# Generated by Django 4.0.2 on 2022-03-05 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_plastic_watercontent_temperature_fibreorientation'),
    ]

    operations = [
        migrations.CreateModel(
            name='FibreStaticCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('K', models.FloatField(max_length=200)),
                ('n', models.FloatField(max_length=200)),
                ('comment', models.CharField(max_length=1000)),
                ('fibre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fibreorientation')),
            ],
        ),
        migrations.CreateModel(
            name='FibreSnCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('Sa', models.CharField(max_length=20000)),
                ('Nf', models.CharField(max_length=20000)),
                ('comment', models.CharField(max_length=1000)),
                ('fibre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.fibreorientation')),
            ],
        ),
    ]
