# Generated by Django 4.0.2 on 2022-03-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_fibreorientation_comment_fibreorientation_rho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibreorientation',
            name='rho',
            field=models.FloatField(blank=True),
        ),
    ]
