# Generated by Django 4.0.2 on 2022-03-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_rubber'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubberTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rubber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rubber')),
            ],
        ),
    ]
