# Generated by Django 4.0.2 on 2022-03-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_rubbertemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubberInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('E', models.FloatField()),
                ('nu', models.FloatField(blank=True)),
                ('rho', models.FloatField(blank=True)),
                ('Rm', models.FloatField(blank=True)),
                ('Re', models.FloatField(blank=True)),
                ('Ru', models.FloatField(blank=True)),
                ('comment', models.CharField(default='', max_length=1000)),
                ('temp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rubbertemp')),
            ],
        ),
    ]
