# Generated by Django 4.0.2 on 2022-03-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_rubberinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rubberinfo',
            name='name',
        ),
    ]
