# Generated by Django 4.0.2 on 2022-03-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_yeoh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeoh',
            name='C_20',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='yeoh',
            name='C_30',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='yeoh',
            name='D_2',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='yeoh',
            name='D_3',
            field=models.CharField(max_length=20000),
        ),
    ]
