# Generated by Django 4.0.2 on 2022-03-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_yeoh_c_20_alter_yeoh_c_30_alter_yeoh_d_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ogden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('nu_1', models.CharField(max_length=20000)),
                ('alfa_1', models.CharField(max_length=20000)),
                ('D_1', models.CharField(max_length=20000)),
                ('nu_2', models.CharField(blank=True, max_length=20000)),
                ('alfa_2', models.CharField(blank=True, max_length=20000)),
                ('D_2', models.CharField(blank=True, max_length=20000)),
                ('nu_3', models.CharField(blank=True, max_length=20000)),
                ('alfa_3', models.CharField(blank=True, max_length=20000)),
                ('D_3', models.CharField(blank=True, max_length=20000)),
                ('comment', models.CharField(max_length=1000)),
                ('rubber_temp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rubbertemp')),
            ],
        ),
    ]
