# Generated by Django 4.0.2 on 2022-03-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_ogden'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeoHooke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('C_10', models.CharField(max_length=20000)),
                ('D_1', models.CharField(max_length=20000)),
                ('comment', models.CharField(max_length=1000)),
                ('rubber_temp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rubbertemp')),
            ],
        ),
    ]
