# Generated by Django 4.0.2 on 2022-03-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_arrudaboyce_d_alter_arrudaboyce_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialcustomcurve',
            old_name='type',
            new_name='curve_type',
        ),
    ]
