# Generated by Django 4.0.2 on 2022-03-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_type_materialcustomcurve_curve_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialcustomcurve',
            name='x_axis_type',
            field=models.CharField(choices=[(' Linear ', ' lin '), (' Logaritmic ', ' log ')], default='lin', max_length=200),
        ),
        migrations.AddField(
            model_name='materialcustomcurve',
            name='y_axis_type',
            field=models.CharField(choices=[(' Linear ', ' lin '), (' Logaritmic ', ' log ')], default='lin', max_length=200),
        ),
    ]
