# Generated by Django 4.0.2 on 2022-03-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_plasticcustomcurve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plasticcustomcurve',
            old_name='material_id',
            new_name='fibre_id',
        ),
    ]
