# Generated by Django 4.0.2 on 2022-03-09 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_rename_material_id_plasticcustomcurve_fibre_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RubberCustomCurve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('curve_type', models.CharField(blank=True, max_length=20000)),
                ('x_axis', models.CharField(blank=True, max_length=20000)),
                ('x_axis_type', models.CharField(choices=[('lin', 'lin'), ('log', 'log')], max_length=200)),
                ('x_value', models.CharField(blank=True, max_length=20000)),
                ('y_axis', models.CharField(blank=True, max_length=20000)),
                ('y_axis_type', models.CharField(choices=[('lin', 'lin'), ('log', 'log')], max_length=200)),
                ('y_value', models.CharField(blank=True, max_length=20000)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('rubber_temp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rubbertemp')),
            ],
        ),
    ]
