# Generated by Django 4.0.2 on 2022-03-09 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_rubbercustomcurve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rubbercustomcurve',
            old_name='curve_type',
            new_name='model_type',
        ),
    ]
