# Generated by Django 4.0.2 on 2022-03-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_alter_cycliccurve_k_alter_cycliccurve_n_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosedynamic',
            name='Dyn_E_min40',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hosedynamic',
            name='Dyn_E_plus100',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hosedynamic',
            name='Dyn_E_plus23',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hosedynamic',
            name='Dyn_nu_min40',
            field=models.FloatField(default=0.495),
        ),
        migrations.AlterField(
            model_name='hosedynamic',
            name='Dyn_nu_plus100',
            field=models.FloatField(default=0.495),
        ),
        migrations.AlterField(
            model_name='hosedynamic',
            name='Dyn_nu_plus23',
            field=models.FloatField(default=0.495),
        ),
        migrations.AlterField(
            model_name='hosestatic',
            name='Stat_E_min40',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hosestatic',
            name='Stat_E_plus100',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hosestatic',
            name='Stat_E_plus23',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hosestatic',
            name='Stat_nu_min40',
            field=models.FloatField(default=0.495),
        ),
        migrations.AlterField(
            model_name='hosestatic',
            name='Stat_nu_plus100',
            field=models.FloatField(default=0.495),
        ),
        migrations.AlterField(
            model_name='hosestatic',
            name='Stat_nu_plus23',
            field=models.FloatField(default=0.495),
        ),
    ]
