# Generated by Django 4.0.2 on 2022-03-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_alter_fibreorientation_e_alter_fibreorientation_re_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hose',
            name='type',
            field=models.CharField(choices=[(' Conti ', ' Conti '), (' Maflow ', ' Maflow '), (' Others ', ' Others ')], max_length=200),
        ),
    ]
